@startuml

[Domain] <<..domain..>>
[Renderer] <<..renderer..>>
[Catalog] <<..catalog..>>

[Tailoring] <<..tailoring..>>
[Domain] <-- [Tailoring]
[Domain] <-- [Renderer]
[Renderer] <-- [Tailoring]

[Domain] <-- [Catalog]
[Renderer] <-- [Catalog]

@enduml