@startuml

[Domain] <<..domain..>>
[Renderer] <<..renderer..>>

[Tailoring] <<..tailoring..>>
[Domain] <-- [Tailoring]
[Renderer] <-- [Tailoring]

[Catalog] <<..catalog..>>
[Domain] <-- [Catalog]
[Renderer] <-- [Catalog]

@enduml