@startuml Ebene3.png
hide empty members

package de.dlr.rpds.tailoringexpert {
    package domain {
        abstract class ResourceMapper
        class ScreeningSheet
        class SelektionsVektor
    }
}

package projekt {
    interface ProjektService {
    }

    interface ProjektPhaseService {
    }

    interface ProjektServiceRepository {
    }

    class ProjektAnlageRequest {
        katalog : String
    }
    ProjektAnlageRequest -> "1" ScreeningSheet : screeningSheet
    ProjektAnlageRequest -> "1" SelektionsVektor : selektionsVektor

    class ProjektController {
        +getProjekte() : ResponseEntity<CollectionModel<EntityModel<ProjektInformationResource>>>
        +createProjekt(version : String, request : ProjektAnlageRequest) : ResponseEntity<Void>
        +getProjekt(projekt : String): ResponseEntity<EntityModel<ProjektInformationResource>>
        +getScreeningSheet(projekt : String) : ResponseEntity<EntityModel<ScreeningSheetResource>>
        +getScreeningSheetDate(projekt : String) : ResponseEntity<byte[]>
        +deleteProjekt(projekt : String) : ResponseEntity<Void>
        +copyProjekt(projekt : String, screeningSheet : MultipartFile) : ResponseEntity<EntityModel<ProjektResource>>
        +addNewTailoring(version : String, request : ProjektAnlageRequest) : ResponseEntity<Void>
        +getSelektionsVektor(projekt : String) : ResponseEntity<EntityModel<SelektionsVektorResource>>
    }
    ProjektController --> "1" ResourceMapper : mapper
    ProjektController --> "1" ProjektService : projektService
    ProjektController --> "1" ProjektServiceRepository : projektServiceRepository
    ProjektController --> "1" TailoringService : tailoringService

}
@enduml
