@startuml Ebene3.png
hide empty members

package domain {
    class DRDElement
}
package renderer {
    interface HTMLTemplateEngine
    class PDFEngine
    class DRDFragment
}

package tailoring {

    interface DocumentCreator {
        createDocument(docId : String, tailoring : Tailoring, placeholders : Map<String, Object>) : File
    }

    class TailoringCatalogPDFDocumentCreator {
    }
    DocumentCreator <|.. TailoringCatalogPDFDocumentCreator
    TailoringCatalogPDFDocumentCreator --> "1" "BiFunction<Chapter<Requirement>, Collection<Phase>, Map<DRD, Set<String>>>" : drdProvider
    TailoringCatalogPDFDocumentCreator --> "1" "Function<Catalog<TailoringRequirement>, Collection<Document>>" : applicableDocumentProvider
    TailoringCatalogPDFDocumentCreator --> "1" HTMLTemplateEngine : templateEngine
    TailoringCatalogPDFDocumentCreator --> "1" PDFEngine : pdfEngine

    class CMPDFDocumentCreator {
    }
    DocumentCreator <|.. CMPDFDocumentCreator
    CMPDFDocumentCreator --> "1" "BiFunction<Chapter<TailoringRequirement>, Collection<Phase>, Map<DRD, Set<String>>>" : drdProvider
    CMPDFDocumentCreator --> "1" HTMLTemplateEngine : templateEngine
    CMPDFDocumentCreator --> "1" PDFEngine : pdfEngine


    class CMElement {
        -level : int
        -level : int
        -number : String
        -name : String
        -requirement : boolean
        -applicable : boolean
    }


    class DRDPDFDocumentCreator {
    }
    DocumentCreator <|.. DRDPDFDocumentCreator
    DRDPDFDocumentCreator --> "1" "BiFunction<Chapter<TailoringRequirement>, Collection<Phase>, Map<DRD, Set<String>>>" : drdProvider
    DRDPDFDocumentCreator --> "1" HTMLTemplateEngine : templateEngine
    DRDPDFDocumentCreator --> "1" PDFEngine : pdfEngine


    class CatalogElement {
        -reference : String
        -position : String
        -chapter : String
        -text : String
        -applicable : boolean
        -level : int
    }


    class ComparisonPDFDocumentCreator {
    }
    DocumentCreator <|.. ComparisonPDFDocumentCreator
    ComparisonPDFDocumentCreator --> "1" HTMLTemplateEngine : templateEngine
    ComparisonPDFDocumentCreator --> "1" PDFEngine : pdfEngine

    class ComparisonElement {
        -section : String
        -title : String
        -selected : boolean
        -changed : boolean
        -changeDate : ZonedDateTime
    }
}
@enduml
