@startuml Ebene3.png
hide empty members

package tailoring {

    interface DocumentCreator {
        createDocument(docId : String, tailoring : Tailoring, placeholders : Map<String, String>) : File
    }

    interface "BiFunction<Kapitel<TailoringRequirement>, Collection<Phase>, Map<DRD, Set<String>>>" as drdSupplier {
    }

    interface "Function<String, File>" as templateSupplier {
    }

    class CMSpreadsheetCreator {
        templateEngine : ITemplateEngine
    }
    CMSpreadsheetCreator --> "1" templateSupplier : templateSupplier
    CMSpreadsheetCreator --> "1" drdSupplier : drdProvider

    class DRDElement {
        title : String
        deliveryDate : String
        requirements : Collection<String>
        number: String
        action : String
    }

    interface "Function<byte[], Map<String, Collection<ImportRequirement>>>" as requirmentFunction {
    }

    class TailoringRequirementExcelFileReader {
    }
    requirementFunction <|.. TailoringRequirementExcelFileReader
}
@enduml