@startuml Ebene3.png
hide empty members

package tailoring {

    interface DocumentCreator {
        createDocument(docId : String, tailoring : Tailoring, placeholders : Map<String, Object>) : File
    }

    interface "BiFunction<Kapitel<TailoringRequirement>, Collection<Phase>, Map<DRD, Set<String>>>" as drdSupplier {
    }

    interface "Function<String, File>" as templateSupplier {
    }

    interface "RendererRequestConfigurationSupplier<RendererRequestConfiguration>" as RendererRequestConfigurationSupplier {
    }

    class TailoringCatalogExcelDocumentCreator {
    }
    DocumentCreator <|-- TailoringCatalogExcelDocumentCreator

    class CMExcelDocumentCreator {
    }
    DocumentCreator <|-- CMExcelDocumentCreator
    CMExcelDocumentCreator --> "1" RendererRequestConfigurationSupplier : requestConfigurationSupplier
    CMExcelDocumentCreator --> "1" drdSupplier : drdProvider

    class DRDElement {
        title : String
        deliveryDate : String
        requirements : Collection<String>
        number: String
        action : String
    }

    interface "Function<byte[], Map<String, Collection<ImportRequirement>>>" as requirementFunction {
    }

    class TailoringRequirementExcelFileReader {
    }
    requirementFunction <|.. TailoringRequirementExcelFileReader
}
@enduml