@startuml

[Domain] <<..domain..>>
[Catalog] <<..catalog..>>
[Requirement] <<..requirement..>>
[ScreeningSheet] <<..screeningsheet..>>
[Tailoring] <<..tailoring..>>
[Project] <<..project..>>
[Repository] <<..repository..>>

[Domain] <-- [Catalog]
[Domain] <-- [Requirement]
[Domain] <-- [ScreeningSheet]
[Domain] <-- [Tailoring]
[Domain] <-- [Project]
[Domain] <-- [Repository]

[Repository] <-- [Catalog]
[Repository] <-- [Project]
[Repository] <-- [Requirement]
[Repository] <-- [ScreeningSheet]
[Repository] <-- [Tailoring]

[ScreeningSheet] <-- [Tailoring]
[ScreeningSheet] <-- [Project]

[Requirement] <-- [Tailoring]

[Tailoring] <-- [Project]

@enduml