@startuml


[Tailoringexpert] <<system>> as tailoringexpert

node Teamsite as teamsite {
}
tailoringexpert -- teamsite : file <

node ECSS as ecss {
}
tailoringexpert -- ecss : file <

node Webbrower  as webbrowser {
}
webbrowser - tailoring



@enduml