@startuml usecases.png

'  left to right direction
  skinparam packageStyle rect
  
  actor "User" as anwender

  rectangle "Project" {
    anwender --> (create project)
    anwender --> (initial tailoring)
    anwender --> (add new tailoring)
  }

  rectangle "Tailoring" {
    anwender --> (edit tailoring)
    anwender --> (de-/select requirement)
    anwender --> (edit requirement text)
    anwender --> (add new requirement)
    anwender --> (compare initial/manual tailoring)
    anwender --> (import tailoring requirements)
  }

  rectangle "Documents" {
    anwender --> (edit document signatures)
    anwender --> (create documents)
  }

  rectangle "File Management" {
    anwender --> (upload file)
    anwender --> (download file)
    anwender --> (delete file)
  }

@enduml