spring.cache.type=jcache
spring.cache.jcache.provider=com.github.benmanes.caffeine.jcache.spi.CaffeineCachingProvider
spring.cache.cache-names=rate-limit-buckets
bucket4j.enabled=true
bucket4j.cache-to-use=jcache"
bucket4j.filters[0].cache-name=rate-limit-buckets
bucket4j.filters[0].url=/api.*
bucket4j.filters[0].strategy=first
bucket4j.filters[0].http-response-body={ "status": 429, "message": "Too many requests" }
bucket4j.filters[0].rate-limits[0].cache-key=getRemoteAddr()
bucket4j.filters[0].rate-limits[0].bandwidths[0].capacity=10
bucket4j.filters[0].rate-limits[0].bandwidths[0].time=1
