@startuml
hide empty members

package eu.tailoringexpert {
    package domain {
        abstract class ResourceMapper
        class MediaTypeProvider
    }
}

package catalog {

    interface CatalogService {
    }

    interface CatalogRepository {
    }

    class CatalogController {
        +postBaseCatalog(catalog : Catalog<BaseRequirement>) : ResponseEntity<Void>
        +getBaseCatalogs() : ResponseEntity<CollectionModel<EntityModel<BaseCatalogVersionResource>>>
        +getBaseCatalog(version : String) : ResponseEntity<Catalog<BaseRequirement>>
        +getBaseCatalogPrint(version : String) : ResponseEntity<byte[]>
        +getBaseCatalogJson(version : String) : ResponseEntity<byte[]>
        +getDocuments(version : String) : ResponseEntity<byte[]>
    }


    CatalogController --> "1" ResourceMapper : mapper
    CatalogController --> "1" CatalogService : catalogService
    CatalogController --> "1" CatalogRepository : catalogRepository
    CatalogController --> "1" MediaTypeProvider : mediaTypeProvider
}
@enduml