@startuml Ebene3.png
hide empty members

package repository {
    interface KatalogRepository
    interface LogoRepository
    interface ProjektRepository
    interface DRDRepository
}
package projekt {

    interface ProjektServiceRepository {
        getKatalog(version : String) : Katalog<AnforderungDefinition>
        createProjekt(katalogVersion : String, projekt : Projekt) : Projekt
        createProjekt(projekt : Projekt) : Projekt
        deleteProjekt(projekt : String): boolean
        getProjekt(projekt : String) : Optional<Projekt>
        addTailoring(projekt : String, tailoring : Tailoring) : Optional<tailoring>
        getProjektInformationen() : Collection<ProjektInformation>
        getProjektInformation(projekt : String) : Optional<ProjektInformation>
        getScreeningSheetDatei(projekt : String) : Optional<byte[]>
        getScreeningSheet(projekt : String) : Optional<ScreeningSheet>
    }

    abstract class JPAProjektServiceRepositoryMapper {
        {abstract} toDomain(entity : ProjektEntity) : Projekt
        {abstract} toEntity(domain : Tailoring) : TailoringEntity
        {abstract} toDomain(entity : TailoringEntity) : Tailoring
        {abstract} toDomain(entity : KatalogEntity) : Katalog<KatalogAnforderung>
        {abstract} createProjekt(domain : Projekt) : ProjektEntity
        {abstract} getProjektInformationen(entity : ProjektEntity) : ProjektInformation
        {abstract} getTailoringInformationen(entity : TailoringEntity) : TailoringInformation
        {abstract} getScreeningSheet(entity : ScreeningSheetEntity) : ScreeningSheet
        resolve(domain : Katalog<AnforderungDefinition>) : KatalogDefinitionEntity
        resolve(domain : Logo) : LogoEntity
        resolve(domain : DRD) : DRDEntity
    }
    JPAProjektServiceRepositoryMapper --> "1" LogoRepository : logoRepository
    JPAProjektServiceRepositoryMapper --> "1" KatalogRepository : katalogRepository
    JPAProjektServiceRepositoryMapper --> "1" DRDRepository : drdRepository

    class JPAProjektServiceRepository {
    }
    ProjektServiceRepository <|.. JPAProjektServiceRepository
    JPAProjektServiceRepository --> "1" JPAProjektServiceRepositoryMapper : mapper
    JPAProjektServiceRepository --> "1" ProjektRepository : projektRepository
    JPAProjektServiceRepository --> "1" KatalogRepository : katalogRepository

}
@enduml