@startuml Ebene3.png
hide empty members

package tailoring {

    interface DocumentService {
        createRequirementDocument(tailoring : Tailoring, creationTimestamp : LocalDateTime): Optional<File>
        createComparisonDocument(tailoring : Tailoring, creationTimestamp : LocalDateTime): Optional<File>
        createAll(tailoring : Tailoring, creationTimestamp : LocalDateTime): Optional<File>
    }

    class TenantDocumentService {
        tenantService : Map<String, DocumentService>
    }
    DocumentService <|.. TenantDocumentService
}
@enduml