@startuml Ebene3.png
hide empty members

package requirement {

    interface RequirementService {
        handleSelected(project : String, tailoring : String, chapter : String, position : String, selected : Boolean) : Optional<TailoringRequirement>;
        handleSelected(project : String, tailoring : String, chapter : String, selected : Boolean) : Optional<Chapter<TailoringRequirement>>
        handleText(project : String, tailoring : String, chapter : String, position : String, text : String) : Optional<TailoringRequirement>
        createRequirement(project : String, tailoring : String, chapter : String, position : String, text : String) : Optional<TailoringRequirement>
    }

    interface RequirementServiceRepository {
        getRequirement(project : String, tailoring : String, chapter : String, position : String) : Optional<TailoringRequirement>
        getChapter(project : String, tailoring : String, chapter : String) : Optional<Chpter<TailoringRequirement>>
        updateRequirement(project : String, tailoring : String, requirement : TailoringRequirement) : Optional<TailoringRequirement>
        updateSelected(project : String, tailoring : String, chapter : Optional<Chapter<TailoringRequirement>) : Optional<Chapter<TailoringRequirement>>
        updateChapter(project : String, tailoring : String, chapter : Chapter<TailoringRequirement>) : Optional<Chapter<TailoringRequirement>>
    }

    interface RequirementModifiablePredicateRepository {
        getTailoringState(project : String, tailoring : String) : Optional<TailoringState>
    }

    interface "BiPredicate<T, U>" as BiPredicate {
         test(t: T, u : U) : boolean
    }
    interface "RequirementModifiablePredicate<String, String>"  as RequirementModifiablePredicate{
    }
    BiPredicate <|-- RequirementModifiablePredicate
    class DefaultRequirementModifiablePredicate {
    }
    RequirementModifiablePredicate <|.. DefaultRequirementModifiablePredicate
    DefaultRequirementModifiablePredicate --> "1" RequirementModifiablePredicateRepository : repository


    class RequirementServiceImpl {
    }
    RequirementService <|-- RequirementServiceImpl
    RequirementServiceImpl --> "1" RequirementServiceRepository : repository
    RequirementServiceImpl --> "1" RequirementModifiablePredicate : predicate

}
@enduml