@startuml Ebene3.png
hide empty members

component openhtmltopdf {
        interface FSDOMMutator {
            mutateDocument(document : org.w3c.dom.Document) : void
        }
}

package renderer {

    class DRDFragment {
        -name : String
        -number : String
        -fragment : String
    }

    interface RendererRequestConfigurationSupplier<RendererRequestConfiguration> {
    }

    class ThymeleafTemplateEngine {
        templateEngine : ITemplateEngine
    }
    ThymeleafTemplateEngine --> "1" RendererRequestConfigurationSupplier : supplier
    HTMLTemplateEngine <|.. ThymeleafTemplateEngine

    class TailoringexpertDOMMutator {
    }
    FSDOMMutator <|.. TailoringexpertDOMMutator

    class PDFEngine {
        baseUri : String
        process(docId : String, html : String, pfadSuffix : String) :  File
    }
    PDFEngine --> "1" TailoringexpertDOMMutator : domMutator
    PDFEngine --> "1" RendererRequestConfigurationSupplier : supplier

}
@enduml