@startuml Ebene3.png
hide empty members

package repository {
    interface BaseCatalogRepository
    interface LogoRepository
    interface DRDRepository
    interface SelectionVectorProfileRepository

}
package catalog {
    interface CatalogServiceRepository {
        createCatalog(catalog : Catalog<BaseRequirement>, validFrom : ZonedDateTime) : Optional<Catalog<BaseRequirement>>
        getCatalog(version : String) : Optional<Catalog<BaseRequirement>>
        existsCatalog( version : String ) : boolean
        limitCatalogValidity( version : String, validUntil : ZonedDateTime ) : Optional<CatalogVersion>
    }

    abstract JPACatalogServiceRepositoryMapper {
        {abstract} createCatalog(domain : Catalog<BaseRequirement>) : BaseCatalogEntity
        {abstract} createCatalog(entity : BaseCatalogEntity) : Catalog<BaseRequirement>
        {abstract} getCatalog(entity: BaseCatalogEntity) : Catalog<BaseRequirement>
        {abstract} createCatalog(domain : DRD) : DRDEntity
        {abstract} toEntity(domain : Chapter<BaseRequirement>) : BaseCatalogChapterEntity
        resolve(domain : Logo) : LogoEntity
        resolve(domain : DRD) : DRDEntity
        addNumber(builder : BaseCatalogChapterEntityBuilder) : void

    }
    JPACatalogServiceRepositoryMapper --> "1" LogoRepository : logoRepository
    JPACatalogServiceRepositoryMapper --> "1" DRDRepository : drdRepository

    class JPACatalogServiceRepository {
    }

    CatalogServiceRepository <|.. JPACatalogServiceRepository
    JPACatalogServiceRepository --> "1" JPACatalogServiceRepositoryMapper : mapper
    JPACatalogServiceRepository --> "1" BaseCatalogRepository : baseCatalogRepository

    abstract JPADocumentServiceRepositoryMapper {
        {abstract} getSelectionVectorProfiles(entity : Catalog<SelectionVectorProfileEntity>) : SelectionVectorProfile
    }

    interface DocumentServiceRepository {
        getSelectionVectorProfiles() : Collection<SelectionVectorProfile>
    }

    class JPADocumentServiceRepository {
    }
    DocumentServiceRepository <|-- JPADocumentServiceRepository
    JPADocumentServiceRepository --> "1" JPADocumentServiceRepositoryMapper : mapper
    JPADocumentServiceRepository --> "1" SelectionVectorProfileRepository : selectionVectorProfileRepository
}

@enduml
