@startuml db.png
skinparam componentStyle uml2
'skinparam linetype ortho

package domain {

    enum DataType {
        SKALAR
        MATRIX
    }

    class ParameterEntity {
        id : Long <<PK>>
        parameterType : String
        category : String
        name : String
        label : String
        value : String
        position : int
    }
    ParameterEntity --> "1" DataType : dataType

    class Phase {
    }


    enum TailoringState {
        CREATED
        ACTIVE
    }

    class DRDEntity {
        id : Long <<PK>>
        number : String
        title : String
        deliveryDate : String
        action : String
    }

    class LogoEntity {
        id : Long <<PK>>
        name : String
        url : String
    }

    class ReferenceEntity <<Embeddable>>{
        text : String
        changed : Boolean
    }
    ReferenceEntity --> "0..1" LogoEntity : logo

    class IdentifierEntity {
        id : Long <<PK>
        type : String
        level : int
        limitations : Set<String>
    }

    class CatalogueRequirementEntity {
        id : Long <<PK>>
        text : String
        postion : String
    }
    CatalogueRequirementEntity --> "0..1" ReferenceEntity : reference
    CatalogueRequirementEntity --> "0..*" Phase : phases <<ordered>>
    CatalogueRequirementEntity --> "0..*" IdentifierEntity : identifiers <<unordered>>
    CatalogueRequirementEntity --> "0..*" DRDEntity : drds <<unordered>>

    class CatalogueChapterEntity {
        id : Long <<PK>>
        name : String
        position : int
        number : String
    }
    CatalogueChapterEntity --> "0..*" CatalogueChapterEntity : chapter <<ordered>>
    CatalogueChapterEntity --> "0..*" CatalogueRequirementEntity : requirements <<ordered>>

    class CatalogEntity {
        id : Long <<PK>>
        version : String
        validFrom : ZonedDateTime
        validUntil : ZonedDateTime
    }
    CatalogEntity --> "1" CatalogueChapterEntity : toc

    enum Phase {
        NULL("0")
        A("A")
        B("B")
        C("C")
        D("D")
        E("E")
        F("F")
    }

    class SelectionVectorEntity {
        id : Long <<PK>>
        levels : Map<String, Integer>
    }

    class SelectionVectorProfileEntity {
        id : Long <<PK>>
        name : String
        internalKey : String <<unique>>
        levels : Map<String, Integer>
    }

    class ScreeningSheetParameterEntity {
        id: Long <<PK>>
        designation : String
        value: Object
    }

    class ScreeningSheetEntity {
        id: Long <<PK>>
        data : byte[]
    }
    ScreeningSheetEntity --> "1..*" ScreeningSheetParameterEntity : parameters
    ScreeningSheetEntity --> "1" SelectionVectorEntity : selectionVector

    class TailoringRequirementEntity {
        id : Long <<PK>>
        text : String
        position : String
        selected : Boolean
        selectionChanged : ZonedDateTime
        textChanged : ZonedDateTime
    }
    TailoringRequirementEntity --> "0..1" ReferenceEntity : reference
    TailoringRequirementEntity --> "0..*" DRDEntity : drds <<unordered>>

    class TailoringCatalogueChapterEntity {
        id : Long <<PK>>
        name : String
        position : int
        chapter : String
        getChapter(chapter : String) : Optional<TailoringCatalogueChapterEntity>
    }
    TailoringCatalogueChapterEntity --> "0..*" TailoringCatalogueChapterEntity : chapters <<ordered>>
    TailoringCatalogueChapterEntity --> "0..*" TailoringRequirementEntity : requirements <<ordered>>

    enum DocumentSignatureType {
        PREPARED("Prepared")
        AGREED("Agreed")
        RELEASED("Released")
    }

    class DocumentEntity {
        id : Long <<PK>>
        name : String
        data : byte []
        hash : String
    }

    class DocumentSignatureEntity {
        faculty : String
        signee : String
        applicable : Boolean
        position : int
    }
    DocumentSignatureEntity --> "1" DocumentSignatureType : type

    class DocumentSigneeEntity {
        id : Long <<PK>>
        faculty : String
        signee : String
        position : int

    }
    DocumentSigneeEntity --> "1" DocumentSignatureType : type

    class NoteEntity {
        id : Long <<Pk>>
        number : Integer
        text : String
        creationTimestamp : ZonedDateTime
    }

    class TailoringEntity {
        id : Long <<Pk>>
        identifier : String
        name : String
        creationTimestamp : ZonedDateTime
    }
    TailoringEntity --> "1" SelectionVectorEntity : selectionVector
    TailoringEntity --> "1" CatalogEntity : baseCatalog
    TailoringEntity --> "1" ScreeningSheetEntity : screeningSheet
    TailoringEntity --> "1..*" Phase : phases
    TailoringEntity --> "1" TailoringCatalogueEntity : catalogue
    TailoringEntity --> "1" TailoringState : state
    TailoringEntity --> "1..*" DocumentSignatureEntity : signatures
    TailoringEntity --> "0..*" DocumentEntity : documents
    TailoringEntity --> "0..*" NoteEntity : notes

    class TailoringCatalogueEntity {
        id : Long <<PK>>
        version : String
    }
    TailoringCatalogueEntity --> "1" TailoringCatalogueChapterEntity : toc

    class ProjectEntity {
        id : Long <<PK>>
        identifier : String <<unique>>
        creationTimestamp : ZonedDateTime
        getTailoring(name : String) : Optional<TailoringEntity>
    }
    ProjectEntity --> "1" CatalogEntity : catalogue
    ProjectEntity --> "1" ScreeningSheetEntity : screeningSheet
    ProjectEntity --> "1..*" TailoringEntity : tailorings


    interface CatalogVersion<<Projektion>> {
        getVersion() : String
        getValidFrom() : ZonedDateTime
        getValidUntil() : ZonedDateTime
    }

    interface AttributeConverter<E, D>

    class ScreeningSheetParameterValueAttributeConverter<Object, String> {
    }
    AttributeConverter <|-- ScreeningSheetParameterValueAttributeConverter

    class ZonedDateTimeAttributeConverter<ZonedDateTime, String> {
    }
    AttributeConverter <|-- ZonedDateTimeAttributeConverter

}

hide empty members
@enduml