@startuml Ebene3.png
hide empty members

package renderer {

    interface HTMLTemplateEngine {
        process(template : String, Map<String, Object> variables) : String
        toXHTML(text :String, placeholders : Map<String, Object>) : String
    }

    class TenantTemplateEngine {
        tenantEngine :  Map<String, HTMLTemplateEngine>
    }
    HTMLTemplateEngine <|.. TenantTemplateEngine

    interface RendererRequestConfigurationSupplier<RendererRequestConfiguration> {
    }

    class TenantRendererConfigurationSupplier {
        templateHome : String
    }
    RendererRequestConfigurationSupplier <|.. TenantRendererConfigurationSupplier

}
@enduml