@startuml Ebene3.png
hide empty members

package renderer {

    interface HTMLTemplateEngine {
        process(template : String, Map<String, Object> variables) : String
        toXHTML(text: String ) : String
        toXHTML(text :String, platzhalter : Map<String, String>) : String
    }

    class TenantTemplateEngine {
        tenantEngine :  Map<String, HTMLTemplateEngine>
    }
    HTMLTemplateEngine <|.. TenantTemplateEngine
}
@enduml