@startuml Ebene3.png
hide empty members

package repository {
    interface JpaRepository<T, ID>

    interface DocumentSigneeRepository<DocumentSigneeEntity, Long> {
        CACHE_SIGNEE : String = "DocumentSigneeRepository#findAll"
        findAll() : List<DocumentSigneeEntity>
    }
    JpaRepository <|-- DocumentSigneeRepository

    interface DRDRepository<DRDEntity, Long> {
        findByNumber(nummbr : String) : DRDEntity
    }
    JpaRepository <|-- DRDRepository

    interface ApplicableDocumentRepository<ApplicableDocumentEntity, Long> {
        findByTitleAndIssueAndRevision(title : String, issue : String, revision : String) : ApplicableDocumentEntity
    }
    JpaRepository <|-- ApplicableDocumentRepository

    interface BaseCatalogRepository<BaseCatalogEntity, Long> {
        CACHE_BASECATALOG : String = "BaseCatalogRepository#BaseCatalog"
        CACHE_BASECATALOGLIST : String = "BaseCatalogRepository#BaseCatalogList"
        findByVersion( version : String, clz: Class<T> ) : T
        findCatalogVersionBy() : Collection<BaseCatalogVersionProjection>
        findCatalogByVersion( version : String ) : BaseCatalogVersionProjection
        save( entity : S) : <S extends BaseCatalogEntity>
        existsByVersion( version : String ) : boolean
        setValidUntilForVersion( version : String, pointOfTime : ZonedDateTime) : int
        deleteCatalogByVersion( version : String ) : void
    }
    JpaRepository <|-- BaseCatalogRepository

    interface LogoRepository<LogoEntity, Long> {
        CACHE_LOGO : String = "LogoRepository#Name"
        findByName(name : String) : LogoEntity
    }
    JpaRepository <|-- LogoRepository

    interface ParameterRepository<ParameterEntity, Long> {
        findByNameIn(names : Collection<String>) : Collection<ParameterEntity>
    }
    JpaRepository <|-- ParameterRepository

    interface TailoringRepository<TailoringEntity, Long> {
    }
    JpaRepository <|-- TailoringRepository

    interface ProjectRepository<ProjectEntity, Long> {
        findByIdentifier(project : String) : ProjectEntity
        deleteByIdentifier(project : String) : Long
        findTailoring(project : String, tailoring : String) : TailoringEntity
        existsTailoring(project : String, tailoring : String) : boolean
    }
    JpaRepository <|-- ProjectRepository

    interface SelectionVectorProfileRepository<SelectionVektorProfileEntity, Long> {
        findByInternalKey(internalKey : String) : SelectionVektorProfileEntity
    }
    JpaRepository <|-- SelectionVectorProfileRepository

    interface TailoringCatalogRepository<TailoringCatalogEntity, Long> {
        existsByVersion( version : String ) : boolean
    }
    JpaRepository <|-- TailoringCatalogRepository
}
@enduml
