@startuml Ebene3.png
hide empty members

package domain {

   class Authentication{
        userId : String
        tenant : String
        accessToken : String
        refreshToken : String
   }

    class AuthenticationRequest {
        userId : String
        password : String
    }

    class AuthenticationRefreshRequest {
        userId : String
        refreshToken : String
    }

   class AuthenticationResource {
       userId : String
       tenant : String
       accessToken : String
       refreshToken : String
   }
   RepresentationModel <|-- AuthenticationResource
}
@enduml
