@startuml Ebene3.png
hide empty members

package katalog {

    interface DokumentCreator {
        createDokument(docId : String, katalog : Katalog<KatalogAnforderung>, platzhalter : Map<String, String>) : Datei
    }

    interface DokumentService {
        createKatalog(katalog : Katalog<KatalogAnforderung>, erstellungszeitpunkt : LocalDateTime) : Optional<Datei>
    }

    interface KatalogService {
        doImport(katalog : Katalog<AnforderungDefinition>) : boolean
        deleteKatalog(version : String) : boolean
        getKatalog(version : String) : Optional<Katalog<KatalogAnforderung>> : Optional<Katalog<KatalogAnforderung>>
        createKatalog(version : String) : Optional<Katalog<KatalogAnforderung>> : Optional<Datei>
    }

    interface KatalogServiceRepository {
        createKatalog(katalog : Katalog<AnforderungDefinition>, gueligAb : ZonedDateTime) : Optional<Katalog<AnforderungDefinition>>
        deleteKatalog(version : String) : boolean
        getKatalog(version : String) : Optional<Katalog<KatalogAnforderung>>
    }

    class KatalogServiceImpl {
    }
    KatalogService <|-- KatalogServiceImpl
    KatalogServiceImpl --> "1" KatalogServiceRepository : repository

}
@enduml