@startuml Ebene3.png
hide empty members

package de.dlr.rpds.tailoring {
    package domain {
        abstract class ResourceMapper
    }
}

package anforderung {
    interface AnforderungService {
    }

    interface AnforderungServiceRepository{
    }

    class AnforderungController {
        +getAnforderung(projekt : String , tailoring : String, kapitel : String, anforderung : String) : ResponseEntity<EntityModel<TailoringAnforderungResource>>
        +updateKapitelAnforderungStatus(projekt : String , tailoring : String, kapitel : String, anforderung : String, ausgewaehlt : Boolean) : ResponseEntity<EntityModel<TailoringeAnforderungResource>>
        +updateAnforderungText(projekt : String , tailoring : String, kapitel : String, anforderung : String, text : String) : ResponseEntity<EntityModel<TailoringAnforderungResource>>
        +updateKapitelAnforderungStatus(projekt : String , phase : String, kapitel : String, ausgewaehlt : Boolean) : ResponseEntity<EntityModel<ProjektPhaseAnforderungGruppeResource>>
        +createAnforderung(projekt : String , tailoring : String, kapitel : String, anforderung : String, text : String) : ResponseEntity<EntityModel<TailoringAnforderungResource>>
    }
    AnforderungController --> "1" ResourceMapper : mapper
    AnforderungController --> "1" AnforderungService : anforderungService
    AnforderungController --> "1" AnforderungServiceRepository : anforderungServiceRepository

}
@enduml
