name: build

on:
  #push:
  #  branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    environment: github 

    permissions:
      contents: read
      packages: write

    container:
      image: ghcr.io/tailoringexpert/maven:3.9-eclipse-25
      #options: -user 1001:127
      env:
        GIT_COMMITTER_NAME: ${{ env.GIT_COMMITTER_NAME }}
        GIT_COMMITTER_EMAIL: ${{ env.GIT_COMMITTER_EMAIL }}
        MAVEN_SERVERID: github
        MAVEN_SNAPSHOTURL: ${{ env.MAVEN_SNAPSHOTURL }}
        MAVEN_RELEASEURL: ${{ env.MAVEN_RELEASEURL }}
        MAVEN_CREDENTIALS_USR: ${{ env.MAVEN_CREDENTIALS_USR }}
        MAVEN_CREDENTIALS_PSW: ${{ env.MAVEN_CREDENTIALS_PSW }}
        SONAR_TOKEN: ${{ env.SONAR_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Branch name
        run: echo running on branch ${GITHUB_REF##*/}

      - name: Checkout badges branch dedicated to storing badges only
        uses: actions/checkout@v7
        with:
          ref: badges
          path: badges

      - name: Set up JDK 25
        uses: actions/setup-java@v6
        with:
          distribution: "temurin"
          java-version: "25"

      - name: Build
        run: |
          mvn --settings .jenkins/settings.xml -Dmaven.repo.local=${{ env.M2_REPO_PATH }} -DskipTests clean compile 
       
      - name: Verify
        run: |
          mvn --settings .jenkins/settings.xml -Dmaven.repo.local=${{ env.M2_REPO_PATH }} verify 
          
      - name: Generate Jacoco Badge
        id: jacoco
        uses: cicirello/jacoco-badge-generator@72266185b7ee48a6fd74eaf0238395cc8b14fef8
        with:
          badges-directory: badges
          generate-branches-badge: true
          jacoco-csv-file: tailoringexpert-coverage/target/site/jacoco-aggregate-ut/jacoco.csv

      - name: Log coverage percentage
        run: |
          echo "coverage = ${{ steps.jacoco.outputs.coverage }}"
          echo "branches = ${{ steps.jacoco.outputs.branches }}"

      - name: Commit and push
        if: ${{ github.event_name != 'pull_request' }}
        run: |
          cd badges
          if [[ `git status --porcelain ./*.svg` ]]; then
            git config --global user.name 'github-actions'
            git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
            git add ./*.svg
            git commit -m "Autogenerated JaCoCo coverage badge" ./*.svg
            git push
          fi

      - name: Upload Jacoco coverage report
        uses: actions/upload-artifact@v6
        with:
          name: jacoco-report
          path: tailoringexpert-coverage/target/site/jacoco-aggregate-ut/
