name: changelog
on:
  workflow_dispatch:
jobs:
  changelog:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate changelog
        id: generate_changelog
        uses: heinrichreimer/github-changelog-generator-action@v2.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          filterByMilestone: true
          pullRequests: false
          prWoLabels: false
          unreleased: false
          dateFormat: "%m.%d.%Y"
          excludeLabels: "duplicate,question,invalid,wontfix,weekly-digest,dependencies,ci"
          output: "CHANGELOG.md"

      - name: Commit and push
        if: ${{ github.event_name != 'pull_request' }}
        run: |
          if [[ `git status --porcelain CHANGELOG.md` ]]; then
            git config --global user.name 'github-actions'
            git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
            git add CHANGELOG.md
            git commit -m "Autogenerated Changelog" CHANGELOG.md
            git push
          fi