name: Changelog
on:
  workflow_dispatch:
jobs:
  changelog:
    runs-on: ubuntu-20.04
    steps:
      - name: "✏️ Generate release changelog"
        uses: heinrichreimer/github-changelog-generator-action@v2.3
        with:
          pullRequests: false
          prWoLabels: false
          dateFormat: "%m.%d.%Y"