name: CI/CD Pipeline

on:
  workflow_dispatch:
    inputs:
      RELEASE_BUILD:
        description: "Create a release"
        type: boolean
        default: false
      DEPLOY:
        description: "Deploy to tailoringxpert repo"
        type: boolean
        default: false
      DEPLOY_TO_CUSTOM_REPOSITORY:
        description: "Select also to maven repo defined by profile custom-maven"
        type: boolean
        default: false
      BRANCH:
        description: "Branch to checkout (Ignored if RELEASE_BUILD is true)"
        type: string
        default: "develop"

jobs:
  skeleton:
    runs-on: ubuntu-latest
    steps:
      - name: Platzhalter
        run: echo "Dieses Skelett dient nur zur UI-Registrierung auf main."
