@startuml Ebene3.png
hide empty members

package catalog {

    interface DocumentCreator {
        createDocument(docId : String, catalog : Catalog<BaseRequirement>, placeholders : Map<String, Object>) : File
    }

    interface DocumentService {
        createCatalog(catalog : Catalog<BaseRequirement>, creationTimestamp : LocalDateTime) : Optional<File>
        createAll(catalog : Catalog<BaseRequirement>,  creationTimestamp : LocalDateTime) : Collection<File>
    }

    interface DocumentServiceRepository {
        getSelectionVectorProfiles() : Collection<SelectionVectorProfile>
    }

    interface CatalogService {
        doImport(katalog : Catalog<BaseCatalogRequirement>) : boolean
        getCatalog(version : String) : Optional<Catalog<BaseRequirement>>
        createCatalog(version : String) : Optional<File>
        createDocuments(version : String) : Optional<File>
    }

    interface CatalogServiceRepository {
        createCatalog(catalog : Catalog<BaseRequirement>, validFrom : ZonedDateTime) : Optional<Catalog<BaseRequirement>>
        getCatalog(version : String) : Optional<Catalog<BaseRequirement>>
        existsCatalog( version : String ) : boolean
    }

    class CatalogServiceImpl {
    }
    CatalogService <|-- CatalogServiceImpl
    CatalogServiceImpl --> "1" CatalogServiceRepository : repository
    CatalogServiceImpl --> "1" DocumentService : documentService

}
@enduml